#!/usr/bin/env bash
# inft-i01 — install a terminal launcher so typing your agent's NAME opens it (Pi).
#
# Works everywhere, but is designed for the CLONE FRAME "iT" terminal: that shell's PATH
# already includes ~/.clone-frame-hub/bin, so a launcher dropped there means the user just
# types e.g. `iclone` and their agent opens — no aliases, no config. A copy also goes to
# ~/.local/bin for normal terminals.
#
#   scripts/install-command.sh [name]      name defaults to identity.json marketplace_name
#
# Idempotent: safe to re-run; it overwrites its own generated launchers only.
set -euo pipefail
cd "$(dirname "$0")/.."
REPO="$(pwd)"

# ── resolve the command name (slug of the agent's name) ──────────────────────────────
RAW="${1:-}"
[ -z "$RAW" ] && RAW="$(node -p "require('./identity.json').marketplace_name" 2>/dev/null || echo iclone)"
slug() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//'; }
CMD="$(slug "$RAW")"; [ -z "$CMD" ] && CMD="iclone"

CFBIN="$HOME/.clone-frame-hub/bin"   # already on the CLONE FRAME iT terminal PATH
LOCALBIN="$HOME/.local/bin"          # conventional user bin for normal terminals
mkdir -p "$CFBIN" "$LOCALBIN"

# ── write a launcher ─────────────────────────────────────────────────────────────────
write_launcher() {
  local target="$1"
  cat > "$target" <<EOF
#!/usr/bin/env bash
# Launch this iNFT / Pi assistant. Generated by inft-i01 scripts/install-command.sh.
# The agent IS a Pi coding agent; -a trusts this project's .pi/ soul + skills so its
# identity (name · iNFT · Pi) and skills load. Args pass through: \`$CMD -p "..."\` works.
AGENT_REPO="$REPO"
cd "\$AGENT_REPO" 2>/dev/null || { echo "agent repo not found: \$AGENT_REPO"; exit 1; }
if command -v pi   >/dev/null 2>&1; then exec pi -a "\$@"; fi
if command -v npx  >/dev/null 2>&1; then exec npx -y @earendil-works/pi-coding-agent -a "\$@"; fi
echo "Pi is not installed — run: bash \"\$AGENT_REPO/scripts/setup.sh\""; exit 127
EOF
  chmod +x "$target"
}

install_named() {
  local cmd="$1"
  write_launcher "$CFBIN/$cmd"
  write_launcher "$LOCALBIN/$cmd"
  printf '  ✓ %-16s → %s\n' "$cmd" "$CFBIN/$cmd (+ ~/.local/bin)"
}

echo "── install-command: launchers for \"$RAW\" ─────────────────────────"
install_named "$CMD"
# Always also install the friendly default `iclone` (unless that IS the name), pointing
# at this same repo — the owner can call the agent by its name OR by `iclone`.
[ "$CMD" != "iclone" ] && install_named "iclone"

echo ""
echo "In the CLONE FRAME iT terminal, just type:  $CMD    (or: iclone)"
case ":$PATH:" in
  *":$LOCALBIN:"*) echo "In a normal terminal too — ~/.local/bin is on your PATH." ;;
  *) echo "For normal (non-iT) terminals, add ~/.local/bin to PATH:";
     echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc" ;;
esac
echo "Underneath it is Pi — 'pi' in this folder is the same agent. It answers to \"$RAW\", \"iNFT\" and \"Pi\"."
