#!/usr/bin/env bash
# inft-i01 — personalize a forged repo. Idempotent and non-destructive.
#
#   personalize.sh "Agent Name"     Set the marketplace name (won't clobber an
#                                   already-personalized name without --force).
#   personalize.sh --apply-owner    Generate the gitignored AGENTS.override.md from
#                                   AGENTS.md + .hermes/owner.local.md, so the owner
#                                   profile reaches the agent but is never committed.
#   Flags: --force  overwrite an existing name.
set -euo pipefail
cd "$(dirname "$0")/.."

PLACEHOLDER="iNFT i01"
SENTINEL="<!-- OWNER-PROFILE-APPLIED -->"

say() { printf '%s\n' "$*"; }

# Hermes injects the project's AGENTS.md into every session, and AGENTS.override.md wins
# over AGENTS.md in the same directory (agent/prompt_builder.py:_load_agents_md). It is the
# standard place for a personal, gitignored overlay next to the committed instructions.
#
# The override REPLACES AGENTS.md rather than adding to it — so it must be self-contained:
# the whole base file, then the profile. It is regenerated from scratch on every run, which
# makes it idempotent AND picks up later AGENTS.md edits.
#
# The soul is NOT written to ~/.hermes/SOUL.md: that is the owner's own global soul, shared
# by all their projects, and no repo script may overwrite it.
apply_owner() {
  local prof=".hermes/owner.local.md"
  local base="AGENTS.md"
  local target="AGENTS.override.md"
  [ -f "$prof" ] || { say "✗ $prof not found. Write the owner profile there first (see owner/OWNER.example.md)."; exit 1; }
  [ -f "$base" ] || { say "✗ $base not found — it is the base this overlay is built from."; exit 1; }

  # NOTE: this header is plain Markdown, NOT an HTML comment. Hermes scans every context
  # file it loads and replaces the WHOLE file with a placeholder if it finds an HTML comment
  # containing ignore/override/system/secret/hidden (tools/threat_patterns.py,
  # "html_comment_injection") — and this file's own name would trip it. The guard below
  # catches the same hazard arriving from $base.
  {
    printf '> GENERATED by `scripts/personalize.sh --apply-owner` — do not edit by hand.\n'
    printf '> Full copy of `%s` plus the local owner profile. Hermes loads this file in\n' "$base"
    printf '> place of `%s`, so it must stay a full copy. Gitignored: it contains PII.\n' "$base"
    printf '> Re-run `scripts/personalize.sh --apply-owner` after editing `%s`.\n\n' "$base"
    cat "$base"
    printf '\n%s\n\n## OWNER PROFILE\n\n' "$SENTINEL"
    cat "$prof"
  } > "$target"
  say "✓ $target generated from $base + $prof (local only)."

  # A blocked context file loses the soul silently — fail loudly instead.
  if grep -qiE '<!--[^>]*(ignore|override|system|secret|hidden)[^>]*-->' "$target"; then
    say "  ⚠ $target contains an HTML comment Hermes will treat as injection — it would"
    say "    load NOTHING. Remove that comment from $base, then re-run this command."
  fi

  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    grep -qxF "$target" .gitignore 2>/dev/null || \
      printf '\n# owner profile overlay (contains PII) — generated by scripts/personalize.sh\n%s\n' "$target" >> .gitignore

    # Safety check: owner files must be ignored.
    for f in "$prof" "$target"; do
      git check-ignore -q "$f" && say "  ✓ $f is gitignored" || say "  ⚠ $f is NOT ignored — do not push until fixed"
    done

    # Legacy: an older personalize.sh appended the profile to SOUL.md and untracked it.
    # Hermes never injected it from there, so that copy is both dead and a PII risk.
    if grep -qF "$SENTINEL" SOUL.md 2>/dev/null; then
      say ""
      say "  ⚠ SOUL.md still carries an owner profile from an older personalize.sh."
      say "    Hermes never loaded it from there. Once you have kept anything you need:"
      say "      git checkout HEAD -- SOUL.md        # restore the sealed soul"
      say "      # remove the 'SOUL.md' line from .gitignore, then:"
      say "      bash scripts/make-manifest.sh"
    fi
  fi
}

set_name() {
  local newname="$1" force="${2:-}"
  local current
  current="$(python3 -c "import json;print(json.load(open('identity.json'))['marketplace_name'])" 2>/dev/null || echo "")"

  if [ "$current" != "$PLACEHOLDER" ] && [ -n "$current" ] && [ "$force" != "--force" ]; then
    say "✓ Already personalized as \"$current\" (idempotent; pass --force to change)."
    return 0
  fi

  python3 - "$newname" <<'PY'
import json, sys
p = "./identity.json"
with open(p) as fh: j = json.load(fh)
j["marketplace_name"] = sys.argv[1]
j.pop("marketplace_name_note", None)
with open(p, "w") as fh: fh.write(json.dumps(j, indent=2) + "\n")
PY
  say "✓ identity.json marketplace_name → \"$newname\""

  # Reflect the name in the metadata template (name field only; leave <...> mint fields).
  python3 - "$newname" <<'PY' 2>/dev/null || true
import json, os, sys
p = "./metadata/metadata.template.json"
if os.path.exists(p):
    with open(p) as fh: j = json.load(fh)
    j["name"] = sys.argv[1]
    with open(p, "w") as fh: fh.write(json.dumps(j, indent=2) + "\n")
PY

  [ -x scripts/make-manifest.sh ] && bash scripts/make-manifest.sh >/dev/null && say "✓ manifest regenerated"
  say "  Your agent answers to \"$newname\", \"iNFT\", and \"Hermes\"."
}

case "${1:-}" in
  ""|-h|--help) say "Usage: personalize.sh \"Agent Name\" [--force]  |  personalize.sh --apply-owner"; exit 0 ;;
  --apply-owner) apply_owner ;;
  *) set_name "$1" "${2:-}" ;;
esac
